{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Tue Oct 29 00:43:23 2013 by ROOT version5.34/05)
//   from TTree tree/GEANT4 simulation for hypTPC
//   found on file: ./grun_with_beam_10.root
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("./grun_with_beam_10.root");
   if (!f) {
      f = new TFile("./grun_with_beam_10.root");
   }
    f->GetObject("tree",tree);

//Declaration of leaves types
   Int_t           ev;
   Double_t        pg[4];
   Int_t           npid;
   Double_t        x0[3][3];
   Double_t        p0[3][5];
   Double_t        pt0[3];
   Double_t        mass0[3];
   Double_t        theta0[3];
   Int_t           gen;
   Int_t           mode;
   Int_t           nttpc;
   Int_t           ntrk[499];
   Int_t           ititpc[499];
   Int_t           idtpc[499];
   Double_t        xtpc[499];
   Double_t        ytpc[499];
   Double_t        ztpc[499];
   Double_t        x0tpc[499];
   Double_t        y0tpc[499];
   Double_t        z0tpc[499];
   Double_t        resoX[499];
   Double_t        pxtpc[499];
   Double_t        pytpc[499];
   Double_t        pztpc[499];
   Double_t        pptpc[499];
   Double_t        masstpc[499];
   Double_t        betatpc[499];
   Double_t        edeptpc[499];
   Double_t        dedxtpc[499];
   Double_t        slengthtpc[499];
   Int_t           laytpc[499];
   Int_t           rowtpc[499];
   Int_t           parentID[499];
   Int_t           nthlay[499];
   Int_t           nthpad[499];
   Int_t           laypad[499][40][250];
   Int_t           ntrtpc;
   Double_t        trpmtpc[12];
   Int_t           trqqtpc[12];
   Double_t        trpxtpc[12];
   Double_t        trpytpc[12];
   Double_t        trpztpc[12];
   Double_t        trpptpc[12];
   Double_t        trpttpc[12];
   Double_t        trpxtpcfit[12];
   Double_t        trpytpcfit[12];
   Double_t        trpztpcfit[12];
   Double_t        trpptpcfit[12];
   Double_t        trpttpcfit[12];
   Double_t        trvtxpxtpc[12];
   Double_t        trvtxpytpc[12];
   Double_t        trvtxpztpc[12];
   Double_t        trvtxpptpc[12];
   Double_t        trvtxxtpc[12];
   Double_t        trvtxytpc[12];
   Double_t        trvtxztpc[12];
   Double_t        trvtxxtpcfit[12];
   Double_t        trvtxytpcfit[12];
   Double_t        trvtxztpcfit[12];
   Double_t        trdetpc[12];
   Double_t        trlentpc[12];
   Double_t        trdedxtpc[12];
   Double_t        trdedxtrtpc[12];
   Int_t           trlaytpc[12];
   Double_t        cir_r[12];
   Double_t        cir_x[12];
   Double_t        cir_z[12];
   Double_t        cir_fit[12];
   Int_t           ntsc;
   Int_t           tidsc[28];
   Int_t           pidsc[28];
   Int_t           didsc[28];
   Double_t        masssc[28];
   Int_t           qqsc[28];
   Double_t        xsc[28];
   Double_t        ysc[28];
   Double_t        zsc[28];
   Double_t        pxsc[28];
   Double_t        pysc[28];
   Double_t        pzsc[28];
   Double_t        ppsc[28];
   Double_t        tofsc[28];
   Int_t           scpID[28];
   Double_t        trvtxpxscint[28];
   Double_t        trvtxpyscint[28];
   Double_t        trvtxpzscint[28];
   Double_t        trvtxppscint[28];
   Double_t        trvtxxscint[28];
   Double_t        trvtxyscint[28];
   Double_t        trvtxzscint[28];
   Double_t        lengthsc[28];
   Int_t           ntac;
   Int_t           tidac[0];
   Int_t           pidac[0];
   Int_t           didac[0];
   Double_t        massac[0];
   Int_t           qqac[0];
   Double_t        xac[0];
   Double_t        yac[0];
   Double_t        zac[0];
   Double_t        pxac[0];
   Double_t        pyac[0];
   Double_t        pzac[0];
   Double_t        ppac[0];
   Double_t        tofac[0];
   Int_t           acpID[0];
   Double_t        trvtxpxac[0];
   Double_t        trvtxpyac[0];
   Double_t        trvtxpzac[0];
   Double_t        trvtxppac[0];
   Double_t        trvtxxac[0];
   Double_t        trvtxyac[0];
   Double_t        trvtxzac[0];
   Double_t        lengthac[0];
   Int_t           ntnbar;
   Int_t           tidnbar[0];
   Int_t           pidnbar[0];
   Int_t           didnbar[0];
   Double_t        massnbar[0];
   Int_t           qqnbar[0];
   Double_t        xnbar[0];
   Double_t        ynbar[0];
   Double_t        znbar[0];
   Double_t        pxnbar[0];
   Double_t        pynbar[0];
   Double_t        pznbar[0];
   Double_t        ppnbar[0];
   Double_t        tofnbar[0];
   Int_t           nbarpID[0];
   Double_t        trvtxpxnbar[0];
   Double_t        trvtxpynbar[0];
   Double_t        trvtxpznbar[0];
   Double_t        trvtxppnbar[0];
   Double_t        trvtxxnbar[0];
   Double_t        trvtxynbar[0];
   Double_t        trvtxznbar[0];
   Double_t        lengthnbar[0];
   Int_t           ntch;
   Int_t           tidch[20];
   Int_t           pidch[20];
   Int_t           didch[20];
   Double_t        massch[20];
   Int_t           qqch[20];
   Double_t        xch[20];
   Double_t        ych[20];
   Double_t        zch[20];
   Double_t        pxch[20];
   Double_t        pych[20];
   Double_t        pzch[20];
   Double_t        ppch[20];
   Double_t        tofch[20];
   Int_t           chpID[20];
   Double_t        trvtxpxch[20];
   Double_t        trvtxpych[20];
   Double_t        trvtxpzch[20];
   Double_t        trvtxppch[20];
   Double_t        trvtxxch[20];
   Double_t        trvtxych[20];
   Double_t        trvtxzch[20];
   Double_t        lengthch[20];
   Int_t           ntftof;
   Int_t           tidftof[25];
   Int_t           pidftof[25];
   Int_t           didftof[25];
   Double_t        massftof[25];
   Int_t           qqftof[25];
   Double_t        xftof[25];
   Double_t        yftof[25];
   Double_t        zftof[25];
   Double_t        pxftof[25];
   Double_t        pyftof[25];
   Double_t        pzftof[25];
   Double_t        ppftof[25];
   Double_t        tofftof[25];
   Int_t           ftofpID[25];
   Double_t        trvtxpxftof[25];
   Double_t        trvtxpyftof[25];
   Double_t        trvtxpzftof[25];
   Double_t        trvtxppftof[25];
   Double_t        trvtxxftof[25];
   Double_t        trvtxyftof[25];
   Double_t        trvtxzftof[25];
   Double_t        lengthftof[25];
   Int_t           ntdc;
   Int_t           tiddc[120];
   Int_t           piddc[120];
   Int_t           diddc[120];
   Double_t        massdc[120];
   Int_t           qqdc[120];
   Double_t        xdc[120];
   Double_t        ydc[120];
   Double_t        zdc[120];
   Double_t        pxdc[120];
   Double_t        pydc[120];
   Double_t        pzdc[120];
   Double_t        ppdc[120];
   Double_t        tofdc[120];
   Int_t           dcpID[120];
   Double_t        trvtxpxdc[120];
   Double_t        trvtxpydc[120];
   Double_t        trvtxpzdc[120];
   Double_t        trvtxppdc[120];
   Double_t        trvtxxdc[120];
   Double_t        trvtxydc[120];
   Double_t        trvtxzdc[120];
   Double_t        lengthdc[120];
   Int_t           targethits;
   Int_t           targetpid[3];
   Int_t           targetparentid[3];
   Int_t           targettid[3];
   Double_t        targetpos[3][3];
   Double_t        targetvtx[3][3];

   // Set branch addresses.
   tree->SetBranchAddress("ev",&ev);
   tree->SetBranchAddress("pg",pg);
   tree->SetBranchAddress("npid",&npid);
   tree->SetBranchAddress("x0",x0);
   tree->SetBranchAddress("p0",p0);
   tree->SetBranchAddress("pt0",pt0);
   tree->SetBranchAddress("mass0",mass0);
   tree->SetBranchAddress("theta0",theta0);
   tree->SetBranchAddress("gen",&gen);
   tree->SetBranchAddress("mode",&mode);
   tree->SetBranchAddress("nttpc",&nttpc);
   tree->SetBranchAddress("ntrk",ntrk);
   tree->SetBranchAddress("ititpc",ititpc);
   tree->SetBranchAddress("idtpc",idtpc);
   tree->SetBranchAddress("xtpc",xtpc);
   tree->SetBranchAddress("ytpc",ytpc);
   tree->SetBranchAddress("ztpc",ztpc);
   tree->SetBranchAddress("x0tpc",x0tpc);
   tree->SetBranchAddress("y0tpc",y0tpc);
   tree->SetBranchAddress("z0tpc",z0tpc);
   tree->SetBranchAddress("resoX",resoX);
   tree->SetBranchAddress("pxtpc",pxtpc);
   tree->SetBranchAddress("pytpc",pytpc);
   tree->SetBranchAddress("pztpc",pztpc);
   tree->SetBranchAddress("pptpc",pptpc);
   tree->SetBranchAddress("masstpc",masstpc);
   tree->SetBranchAddress("betatpc",betatpc);
   tree->SetBranchAddress("edeptpc",edeptpc);
   tree->SetBranchAddress("dedxtpc",dedxtpc);
   tree->SetBranchAddress("slengthtpc",slengthtpc);
   tree->SetBranchAddress("laytpc",laytpc);
   tree->SetBranchAddress("rowtpc",rowtpc);
   tree->SetBranchAddress("parentID",parentID);
   tree->SetBranchAddress("nthlay",nthlay);
   tree->SetBranchAddress("nthpad",nthpad);
   tree->SetBranchAddress("laypad",laypad);
   tree->SetBranchAddress("ntrtpc",&ntrtpc);
   tree->SetBranchAddress("trpmtpc",trpmtpc);
   tree->SetBranchAddress("trqqtpc",trqqtpc);
   tree->SetBranchAddress("trpxtpc",trpxtpc);
   tree->SetBranchAddress("trpytpc",trpytpc);
   tree->SetBranchAddress("trpztpc",trpztpc);
   tree->SetBranchAddress("trpptpc",trpptpc);
   tree->SetBranchAddress("trpttpc",trpttpc);
   tree->SetBranchAddress("trpxtpcfit",trpxtpcfit);
   tree->SetBranchAddress("trpytpcfit",trpytpcfit);
   tree->SetBranchAddress("trpztpcfit",trpztpcfit);
   tree->SetBranchAddress("trpptpcfit",trpptpcfit);
   tree->SetBranchAddress("trpttpcfit",trpttpcfit);
   tree->SetBranchAddress("trvtxpxtpc",trvtxpxtpc);
   tree->SetBranchAddress("trvtxpytpc",trvtxpytpc);
   tree->SetBranchAddress("trvtxpztpc",trvtxpztpc);
   tree->SetBranchAddress("trvtxpptpc",trvtxpptpc);
   tree->SetBranchAddress("trvtxxtpc",trvtxxtpc);
   tree->SetBranchAddress("trvtxytpc",trvtxytpc);
   tree->SetBranchAddress("trvtxztpc",trvtxztpc);
   tree->SetBranchAddress("trvtxxtpcfit",trvtxxtpcfit);
   tree->SetBranchAddress("trvtxytpcfit",trvtxytpcfit);
   tree->SetBranchAddress("trvtxztpcfit",trvtxztpcfit);
   tree->SetBranchAddress("trdetpc",trdetpc);
   tree->SetBranchAddress("trlentpc",trlentpc);
   tree->SetBranchAddress("trdedxtpc",trdedxtpc);
   tree->SetBranchAddress("trdedxtrtpc",trdedxtrtpc);
   tree->SetBranchAddress("trlaytpc",trlaytpc);
   tree->SetBranchAddress("cir_r",cir_r);
   tree->SetBranchAddress("cir_x",cir_x);
   tree->SetBranchAddress("cir_z",cir_z);
   tree->SetBranchAddress("cir_fit",cir_fit);
   tree->SetBranchAddress("ntsc",&ntsc);
   tree->SetBranchAddress("tidsc",tidsc);
   tree->SetBranchAddress("pidsc",pidsc);
   tree->SetBranchAddress("didsc",didsc);
   tree->SetBranchAddress("masssc",masssc);
   tree->SetBranchAddress("qqsc",qqsc);
   tree->SetBranchAddress("xsc",xsc);
   tree->SetBranchAddress("ysc",ysc);
   tree->SetBranchAddress("zsc",zsc);
   tree->SetBranchAddress("pxsc",pxsc);
   tree->SetBranchAddress("pysc",pysc);
   tree->SetBranchAddress("pzsc",pzsc);
   tree->SetBranchAddress("ppsc",ppsc);
   tree->SetBranchAddress("tofsc",tofsc);
   tree->SetBranchAddress("scpID",scpID);
   tree->SetBranchAddress("trvtxpxscint",trvtxpxscint);
   tree->SetBranchAddress("trvtxpyscint",trvtxpyscint);
   tree->SetBranchAddress("trvtxpzscint",trvtxpzscint);
   tree->SetBranchAddress("trvtxppscint",trvtxppscint);
   tree->SetBranchAddress("trvtxxscint",trvtxxscint);
   tree->SetBranchAddress("trvtxyscint",trvtxyscint);
   tree->SetBranchAddress("trvtxzscint",trvtxzscint);
   tree->SetBranchAddress("lengthsc",lengthsc);
   tree->SetBranchAddress("ntac",&ntac);
   tree->SetBranchAddress("tidac",&tidac);
   tree->SetBranchAddress("pidac",&pidac);
   tree->SetBranchAddress("didac",&didac);
   tree->SetBranchAddress("massac",&massac);
   tree->SetBranchAddress("qqac",&qqac);
   tree->SetBranchAddress("xac",&xac);
   tree->SetBranchAddress("yac",&yac);
   tree->SetBranchAddress("zac",&zac);
   tree->SetBranchAddress("pxac",&pxac);
   tree->SetBranchAddress("pyac",&pyac);
   tree->SetBranchAddress("pzac",&pzac);
   tree->SetBranchAddress("ppac",&ppac);
   tree->SetBranchAddress("tofac",&tofac);
   tree->SetBranchAddress("acpID",&acpID);
   tree->SetBranchAddress("trvtxpxac",&trvtxpxac);
   tree->SetBranchAddress("trvtxpyac",&trvtxpyac);
   tree->SetBranchAddress("trvtxpzac",&trvtxpzac);
   tree->SetBranchAddress("trvtxppac",&trvtxppac);
   tree->SetBranchAddress("trvtxxac",&trvtxxac);
   tree->SetBranchAddress("trvtxyac",&trvtxyac);
   tree->SetBranchAddress("trvtxzac",&trvtxzac);
   tree->SetBranchAddress("lengthac",&lengthac);
   tree->SetBranchAddress("ntnbar",&ntnbar);
   tree->SetBranchAddress("tidnbar",&tidnbar);
   tree->SetBranchAddress("pidnbar",&pidnbar);
   tree->SetBranchAddress("didnbar",&didnbar);
   tree->SetBranchAddress("massnbar",&massnbar);
   tree->SetBranchAddress("qqnbar",&qqnbar);
   tree->SetBranchAddress("xnbar",&xnbar);
   tree->SetBranchAddress("ynbar",&ynbar);
   tree->SetBranchAddress("znbar",&znbar);
   tree->SetBranchAddress("pxnbar",&pxnbar);
   tree->SetBranchAddress("pynbar",&pynbar);
   tree->SetBranchAddress("pznbar",&pznbar);
   tree->SetBranchAddress("ppnbar",&ppnbar);
   tree->SetBranchAddress("tofnbar",&tofnbar);
   tree->SetBranchAddress("nbarpID",&nbarpID);
   tree->SetBranchAddress("trvtxpxnbar",&trvtxpxnbar);
   tree->SetBranchAddress("trvtxpynbar",&trvtxpynbar);
   tree->SetBranchAddress("trvtxpznbar",&trvtxpznbar);
   tree->SetBranchAddress("trvtxppnbar",&trvtxppnbar);
   tree->SetBranchAddress("trvtxxnbar",&trvtxxnbar);
   tree->SetBranchAddress("trvtxynbar",&trvtxynbar);
   tree->SetBranchAddress("trvtxznbar",&trvtxznbar);
   tree->SetBranchAddress("lengthnbar",&lengthnbar);
   tree->SetBranchAddress("ntch",&ntch);
   tree->SetBranchAddress("tidch",tidch);
   tree->SetBranchAddress("pidch",pidch);
   tree->SetBranchAddress("didch",didch);
   tree->SetBranchAddress("massch",massch);
   tree->SetBranchAddress("qqch",qqch);
   tree->SetBranchAddress("xch",xch);
   tree->SetBranchAddress("ych",ych);
   tree->SetBranchAddress("zch",zch);
   tree->SetBranchAddress("pxch",pxch);
   tree->SetBranchAddress("pych",pych);
   tree->SetBranchAddress("pzch",pzch);
   tree->SetBranchAddress("ppch",ppch);
   tree->SetBranchAddress("tofch",tofch);
   tree->SetBranchAddress("chpID",chpID);
   tree->SetBranchAddress("trvtxpxch",trvtxpxch);
   tree->SetBranchAddress("trvtxpych",trvtxpych);
   tree->SetBranchAddress("trvtxpzch",trvtxpzch);
   tree->SetBranchAddress("trvtxppch",trvtxppch);
   tree->SetBranchAddress("trvtxxch",trvtxxch);
   tree->SetBranchAddress("trvtxych",trvtxych);
   tree->SetBranchAddress("trvtxzch",trvtxzch);
   tree->SetBranchAddress("lengthch",lengthch);
   tree->SetBranchAddress("ntftof",&ntftof);
   tree->SetBranchAddress("tidftof",tidftof);
   tree->SetBranchAddress("pidftof",pidftof);
   tree->SetBranchAddress("didftof",didftof);
   tree->SetBranchAddress("massftof",massftof);
   tree->SetBranchAddress("qqftof",qqftof);
   tree->SetBranchAddress("xftof",xftof);
   tree->SetBranchAddress("yftof",yftof);
   tree->SetBranchAddress("zftof",zftof);
   tree->SetBranchAddress("pxftof",pxftof);
   tree->SetBranchAddress("pyftof",pyftof);
   tree->SetBranchAddress("pzftof",pzftof);
   tree->SetBranchAddress("ppftof",ppftof);
   tree->SetBranchAddress("tofftof",tofftof);
   tree->SetBranchAddress("ftofpID",ftofpID);
   tree->SetBranchAddress("trvtxpxftof",trvtxpxftof);
   tree->SetBranchAddress("trvtxpyftof",trvtxpyftof);
   tree->SetBranchAddress("trvtxpzftof",trvtxpzftof);
   tree->SetBranchAddress("trvtxppftof",trvtxppftof);
   tree->SetBranchAddress("trvtxxftof",trvtxxftof);
   tree->SetBranchAddress("trvtxyftof",trvtxyftof);
   tree->SetBranchAddress("trvtxzftof",trvtxzftof);
   tree->SetBranchAddress("lengthftof",lengthftof);
   tree->SetBranchAddress("ntdc",&ntdc);
   tree->SetBranchAddress("tiddc",tiddc);
   tree->SetBranchAddress("piddc",piddc);
   tree->SetBranchAddress("diddc",diddc);
   tree->SetBranchAddress("massdc",massdc);
   tree->SetBranchAddress("qqdc",qqdc);
   tree->SetBranchAddress("xdc",xdc);
   tree->SetBranchAddress("ydc",ydc);
   tree->SetBranchAddress("zdc",zdc);
   tree->SetBranchAddress("pxdc",pxdc);
   tree->SetBranchAddress("pydc",pydc);
   tree->SetBranchAddress("pzdc",pzdc);
   tree->SetBranchAddress("ppdc",ppdc);
   tree->SetBranchAddress("tofdc",tofdc);
   tree->SetBranchAddress("dcpID",dcpID);
   tree->SetBranchAddress("trvtxpxdc",trvtxpxdc);
   tree->SetBranchAddress("trvtxpydc",trvtxpydc);
   tree->SetBranchAddress("trvtxpzdc",trvtxpzdc);
   tree->SetBranchAddress("trvtxppdc",trvtxppdc);
   tree->SetBranchAddress("trvtxxdc",trvtxxdc);
   tree->SetBranchAddress("trvtxydc",trvtxydc);
   tree->SetBranchAddress("trvtxzdc",trvtxzdc);
   tree->SetBranchAddress("lengthdc",lengthdc);
   tree->SetBranchAddress("targethits",&targethits);
   tree->SetBranchAddress("targetpid",targetpid);
   tree->SetBranchAddress("targetparentid",targetparentid);
   tree->SetBranchAddress("targettid",targettid);
   tree->SetBranchAddress("targetpos",targetpos);
   tree->SetBranchAddress("targetvtx",targetvtx);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// tree->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = tree->GetEntries();

   Long64_t nbytes = 0;
//   for (Long64_t i=0; i<nentries;i++) {
//      nbytes += tree->GetEntry(i);
//   }
}
